# TCL File Generated by Component Editor 13.0sp1
# Tue Dec 23 15:33:29 ICT 2025
# DO NOT MODIFY


# 
# DMA "DMA" v1.0
#  2025.12.23.15:33:29
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module DMA
# 
set_module_property DESCRIPTION ""
set_module_property NAME DMA
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME DMA
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL DMAFinal
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file DMAFinal.v VERILOG PATH DMAFinal.v TOP_LEVEL_FILE
add_fileset_file control_slave.v VERILOG PATH control_slave.v
add_fileset_file FIFO.v VERILOG PATH FIFO.v
add_fileset_file read_master.v VERILOG PATH read_master.v
add_fileset_file write_master.v VERILOG PATH write_master.v

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL DMAFinal
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file DMAFinal.v VERILOG PATH DMAFinal.v
add_fileset_file control_slave.v VERILOG PATH control_slave.v
add_fileset_file FIFO.v VERILOG PATH FIFO.v
add_fileset_file read_master.v VERILOG PATH read_master.v
add_fileset_file write_master.v VERILOG PATH write_master.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point CONTROL
# 
add_interface CONTROL avalon end
set_interface_property CONTROL addressUnits WORDS
set_interface_property CONTROL associatedClock clk
set_interface_property CONTROL associatedReset reset
set_interface_property CONTROL bitsPerSymbol 8
set_interface_property CONTROL burstOnBurstBoundariesOnly false
set_interface_property CONTROL burstcountUnits WORDS
set_interface_property CONTROL explicitAddressSpan 0
set_interface_property CONTROL holdTime 0
set_interface_property CONTROL linewrapBursts false
set_interface_property CONTROL maximumPendingReadTransactions 0
set_interface_property CONTROL readLatency 0
set_interface_property CONTROL readWaitStates 0
set_interface_property CONTROL readWaitTime 0
set_interface_property CONTROL setupTime 0
set_interface_property CONTROL timingUnits Cycles
set_interface_property CONTROL writeWaitTime 0
set_interface_property CONTROL ENABLED true
set_interface_property CONTROL EXPORT_OF ""
set_interface_property CONTROL PORT_NAME_MAP ""
set_interface_property CONTROL SVD_ADDRESS_GROUP ""

add_interface_port CONTROL iWrite write Input 1
add_interface_port CONTROL iAddress address Input 3
add_interface_port CONTROL iWritedata writedata Input 32
add_interface_port CONTROL oReaddata readdata Output 32
add_interface_port CONTROL iRead read Input 1
add_interface_port CONTROL iChipselect_n chipselect_n Input 1
set_interface_assignment CONTROL embeddedsw.configuration.isFlash 0
set_interface_assignment CONTROL embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment CONTROL embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment CONTROL embeddedsw.configuration.isPrintableDevice 0


# 
# connection point READ
# 
add_interface READ avalon start
set_interface_property READ addressUnits SYMBOLS
set_interface_property READ associatedClock clk
set_interface_property READ associatedReset reset
set_interface_property READ bitsPerSymbol 8
set_interface_property READ burstOnBurstBoundariesOnly false
set_interface_property READ burstcountUnits WORDS
set_interface_property READ doStreamReads false
set_interface_property READ doStreamWrites false
set_interface_property READ holdTime 0
set_interface_property READ linewrapBursts false
set_interface_property READ maximumPendingReadTransactions 0
set_interface_property READ readLatency 0
set_interface_property READ readWaitTime 0
set_interface_property READ setupTime 0
set_interface_property READ timingUnits Cycles
set_interface_property READ writeWaitTime 0
set_interface_property READ ENABLED true
set_interface_property READ EXPORT_OF ""
set_interface_property READ PORT_NAME_MAP ""
set_interface_property READ SVD_ADDRESS_GROUP ""

add_interface_port READ iRM_readdatavalid readdatavalid Input 1
add_interface_port READ iRM_waitrequest waitrequest Input 1
add_interface_port READ iRM_readdata readdata Input 32
add_interface_port READ oRM_read read Output 1
add_interface_port READ oRM_readaddress address Output 32


# 
# connection point WRITE
# 
add_interface WRITE avalon start
set_interface_property WRITE addressUnits SYMBOLS
set_interface_property WRITE associatedClock clk
set_interface_property WRITE associatedReset reset
set_interface_property WRITE bitsPerSymbol 8
set_interface_property WRITE burstOnBurstBoundariesOnly false
set_interface_property WRITE burstcountUnits WORDS
set_interface_property WRITE doStreamReads false
set_interface_property WRITE doStreamWrites false
set_interface_property WRITE holdTime 0
set_interface_property WRITE linewrapBursts false
set_interface_property WRITE maximumPendingReadTransactions 0
set_interface_property WRITE readLatency 0
set_interface_property WRITE readWaitTime 0
set_interface_property WRITE setupTime 0
set_interface_property WRITE timingUnits Cycles
set_interface_property WRITE writeWaitTime 0
set_interface_property WRITE ENABLED true
set_interface_property WRITE EXPORT_OF ""
set_interface_property WRITE PORT_NAME_MAP ""
set_interface_property WRITE SVD_ADDRESS_GROUP ""

add_interface_port WRITE oWM_write write Output 1
add_interface_port WRITE oWM_writeaddress address Output 32
add_interface_port WRITE oWM_writedata writedata Output 32
add_interface_port WRITE iWM_waitrequest waitrequest Input 1


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk iClk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset iReset_n reset_n Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clk
set_interface_property conduit_end associatedReset reset
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end debug_WM_done export Output 1

